# Этап сборки
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Этап запуска
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

# Копируем конфиг, чтобы поддерживать SPA (роутинг на стороне клиента)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]